### PR TITLE
Fix keep_alive_for by sending an initial keep alive request, otherwise the request hangs forever.

### PR DESCRIPTION
**Pull request by dtzxporter**
Title.

### CODE REVIEW

**Comment by dtzxporter** [comment]
Possible to get a crates.io release after this one? :D

**Review by lodrem — DISMISSED** [review]
LGTM. Thanks for the fix.

**Comment by lodrem** [comment]
> Possible to get a crates.io release after this one? :D

Sure.

**Comment by dtzxporter** [comment]
-- I made it also check the initial request before returning the stream.

**Review by lodrem — APPROVED** [review]
LGTM

**Pull request merged**
