### PR TITLE
Fix panic and dead loop when etcd is down

### PR DESCRIPTION
**Pull request by frostyplanet**
Fix problems in both lease and watch

### CODE REVIEW

**Comment by frostyplanet** [comment]
ping

**Comment by luncj** [comment]
@frostyplanet Sorry for the delay in responding. Would you mind rebasing against `upstream/master`. Thanks.

**Comment by frostyplanet** [comment]
@lodrem  already rebased

**Comment by frostyplanet** [comment]
@lodrem  It seams you are rewriting API,  consider to solve this problem?

**Comment by lodrem** [comment]
@frostyplanet will do. Thanks a lot for this PR!

**Comment by lodrem** [comment]
gg

**Pull request closed without merging**
